stages:
  - build
  - deploy

variables:
  IMAGE_NAME: homelab-vite
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

cache:
  paths:
    - app/node_modules/

build_image:
  stage: build
  tags:
    - podman
  script:
    - cd app
    - npm ci
    - npm run build
    - cd ..
    - podman build -t $IMAGE_NAME:$IMAGE_TAG .
    - podman save $IMAGE_NAME:$IMAGE_TAG > image.tar
  artifacts:
    paths:
      - image.tar
    expire_in: 1 hour
  only:
    - main

deploy_app:
  stage: deploy
  tags:
    - podman
  script:
    - podman load < image.tar
    - podman tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
    - podman-compose -f compose.yml down || true
    - podman-compose -f compose.yml up -d
  environment: production
  only:
    - main
